# ########################################################################
# Disclaimer:
# Code for example use only, not for production use
# This code has not been thoroughly tested under all conditions so,
# please do your own verification before using this code.
#
# Amazon Web Services makes no warranties, express or implied, in this document.
# Amazon Web Services (AWS) may have patents, patent applications, trademarks,
# copyrights, or other intellectual property rights covering subject matter in
# this document. Except as expressly provided in any written license agreement
# from AWS, our provision of this document does not give you any license to these
# patents, trademarks, copyrights, or other intellectual property. The descriptions
# of other companies products in this document, if any, are provided only as a
# convenience to you. Any such references should not be considered an endorsement
# or support by AWS. AWS cannot guarantee their accuracy, and the products may
# change over time. Also, the descriptions are intended as brief highlights to aid
# understanding, rather than as thorough coverage. For authoritative descriptions
# of these products, please consult their respective manufacturers.
# Copyright © 2023 Amazon Web Services, Inc. and/or its affiliates. All rights reserved.
# ########################################################################

Description: Destination S3 Bucket Policy Resource

Parameters:
  destinationS3Bucket:
    Type: String
    Description: Enter name of the source S3 bucket
  dsRole:
    Type: String
    Description: Enter ARN of the DataSync role
    
Resources:

  destinationBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref destinationS3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "s3:GetBucketLocation"
              - "s3:ListBucket"
              - "s3:ListBucketMultipartUploads"
              - "s3:AbortMultipartUpload"
              - "s3:DeleteObject"
              - "s3:GetObject"
              - "s3:GetEncryptionConfiguration"
              - "s3:ListMultipartUploadParts"
              - "s3:PutObject"
              - "s3:PutEncryptionConfiguration"
              - "s3:GetObjectTagging"
              - "s3:PutObjectTagging"
            Principal: 
              AWS:
                - !Ref dsRole
            Resource: 
              - !Sub "arn:aws:s3:::${destinationS3Bucket}"
              - !Sub "arn:aws:s3:::${destinationS3Bucket}/*"
          - Effect: Allow
            Principal: 
              AWS:
                - !Ref dsRole
            Action:
              - "s3:ListBucket"
              - "s3:PutObject"
              - "s3:GetEncryptionConfiguration"
              - "s3:PutEncryptionConfiguration"
            Resource: 
              - !Sub "arn:aws:s3:::${destinationS3Bucket}"
              - !Sub "arn:aws:s3:::${destinationS3Bucket}/*"
